WebFindTutor_Client/Controllers/AdminInstructorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using WebFindTutor_Client.Models;

namespace WebFindTutor_Client.Controllers
{
    public class AdminInstructorController : Controller
    {
        // GET: AdminInstructor
        public ActionResult Index()
        {
            IEnumerable<InstructorModel> istList;
            HttpResponseMessage response = GlobalVariables.WebApiClient.GetAsync("INSTRUCTORs").Result;
            istList = response.Content.ReadAsAsync<IEnumerable<InstructorModel>>().Result;
            return View(istList);
        }

        public ActionResult AddOrEdit(int id = 0)
        {
            if(id ==0)
            {
                return View(new InstructorModel());
            }
            else
            {
                HttpResponseMessage response = GlobalVariables.WebApiClient.GetAsync("INSTRUCTORs/"+id.ToString()).Result;
                return View(response.Content.ReadAsAsync<InstructorModel>().Result);
            }
            
        }
        [HttpPost]
        public ActionResult AddOrEdit(InstructorModel emp)
        {
            if(emp.Instructor_ID == 0)
            {
                HttpResponseMessage response = GlobalVariables.WebApiClient.PostAsJsonAsync("INSTRUCTORs", emp).Result;
                TempData["SuccessMessage"] = "Saved Successfully";
            }
            else {
                HttpResponseMessage response = GlobalVariables.WebApiClient.PutAsJsonAsync("INSTRUCTORs/"+emp.Instructor_ID, emp).Result;
                TempData["SuccessMessage"] = "Updated Successfully";
            }
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int id)
        {
            HttpResponseMessage response = GlobalVariables.WebApiClient.DeleteAsync("INSTRUCTORs/" + id.ToString()).Result;
            TempData["SuccessMessage"] = "Deleted Successfully";
            return RedirectToAction("Index");
        }
    }
}

WebFindTutor_Client/Views/AdminInstructor/AddOrEdit.cshtml
@model WebFindTutor_Client.Models.InstructorModel

@{
    ViewBag.Title = "AddOrEdit";
}

<h2>AddOrEdit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>InstructorModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
                @Html.LabelFor(model => model.Instructor_ID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Instructor_ID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Instructor_ID, "", new { @class = "text-danger" })
                </div>
            </div>*@
        @Html.HiddenFor(model => model.Instructor_ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Instructor_FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Instructor_FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Instructor_FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Instructor_LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Instructor_LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Instructor_LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Instructor_TelNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Instructor_TelNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Instructor_TelNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.Instructor_location, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Instructor_location, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Instructor_location, "", new { @class = "text-danger" })
                </div>
            </div>*@

        @*<div class="form-group">
                @Html.LabelFor(model => model.Instructor_Pic, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Instructor_Pic, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Instructor_Pic, "", new { @class = "text-danger" })
                </div>
            </div>*@

        @*<div class="form-group">
                @Html.LabelFor(model => model.Instructor_University, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Instructor_University, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Instructor_University, "", new { @class = "text-danger" })
                </div>
            </div>*@

        @*<div class="form-group">
                @Html.LabelFor(model => model.Course_ID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Course_ID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Course_ID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Subject_ID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Subject_ID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Subject_ID, "", new { @class = "text-danger" })
                </div>
            </div>*@

        @*<div class="form-group">
                @Html.LabelFor(model => model.Faculty, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Faculty, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Faculty, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Department, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Department, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Department, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Confirmation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Confirmation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Confirmation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-default" />
                <input type="reset" value="Reset" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
}

WebFindTutor_Client/Views/AdminInstructor/Index.cshtml
@model IEnumerable<WebFindTutor_Client.Models.InstructorModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    <a href="@Url.Action("AddOrEdit","AdminInstructor")" class="btn btn-default"><i class="fa fa-plus"></i>Create New</a>
</p>

<table id="AdminInstructorTable" class="table table-striped table-bordered" style="width:100%">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Instructor_ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Instructor_FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Instructor_LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Instructor_TelNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Instructor_location)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Instructor_Pic)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Instructor_University)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Course_ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Subject_ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Faculty)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Department)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Confirmation)
            </th>
            <th></th>
        </tr>
    </thead>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Instructor_ID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Instructor_FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Instructor_LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Instructor_TelNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Instructor_location)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Instructor_Pic)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Instructor_University)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Course_ID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Subject_ID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Faculty)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Department)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Confirmation)
                </td>
                <td>
                    <a href="@Url.Action("AddOrEdit","AdminInstructor",new { id = item.Instructor_ID })" class="btn btn-default"><i class="fa fa-pencil"></i>Edit</a>
                    <a onclick="Delete(@item.Instructor_ID)" class="btn btn-default"><i class="fa fa-trash"></i>Delete</a>
                </td>
            </tr>
        }

</table>
@section scripts{
    <script>
        $(function () {
            var successMessage = '@TempData["SuccessMessage"]';
            if (successMessage != '')
                alertify.success(successMessage);
        });
        function Delete(id) {
            alertify.confirm('Web Api CRUD Operations', 'Are You Sure to Delete this Record?', function () {
                window.location.href = '@Url.Action("Delete","AdminInstructor")/' + id;
            },null );
        }
        </script>
    }